//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsType
    {
        public int ID_NewsType { get; set; }
        public string Title_NewsType { get; set; }
    }
}
